# Generated by Django 2.2.10 on 2020-06-29 05:05

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoneProjects',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to=projects.models.upload_location)),
                ('frontend', models.CharField(max_length=256)),
                ('backend', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'Our Projects',
            },
        ),
    ]
