# Generated by Django 2.2.10 on 2020-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200713_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneprojects',
            name='backend',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='doneprojects',
            name='body',
            field=models.TextField(default='this is default text', max_length=5000),
        ),
    ]
