# Generated by Django 2.2.10 on 2020-07-16 19:23

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200713_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneprojects',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to=projects.models.upload_location),
        ),
    ]
