# Generated by Django 2.2.10 on 2020-06-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField(max_length=2000)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='date_submitted')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
