# Generated by Django 2.2.10 on 2020-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(default='name', max_length=254, null=True),
        ),
    ]
