# Generated by Django 2.2.10 on 2020-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20200702_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
