# Generated by Django 2.2.10 on 2020-06-29 05:05

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to=services.models.upload_location)),
                ('body', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to=services.models.upload_location)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'Our Services',
            },
        ),
    ]
