# Generated by Django 2.2.10 on 2020-06-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('accounts', models.TextField(default='facebook: , twitter: , linkedin: , instagram: ', max_length=256)),
            ],
            options={
                'verbose_name': 'Members',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
