# Generated by Django 2.2.10 on 2020-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='accounts',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='github_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='linkedin_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
