# Generated by Django 2.2.10 on 2020-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200710_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='github_account',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='linkedin_account',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='position',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='skills',
            field=models.CharField(max_length=256),
        ),
    ]
